name: Build and Deploy Pipeline

on:
  push:
    branches:
      - main # Change this if your default branch is different
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Using a more stable version
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci # More reliable than npm install for CI environments
      
      - name: Run tests
        run: npm test
        # Add continue-on-error: true if you want pipeline to continue even if tests fail
      
      - name: Build project
        run: npm run build
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-files
          path: dist/ # Make sure this matches your output directory
          retention-days: 1
  
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    # Only deploy on push to main, not on pull requests
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-files
          path: dist
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Deploy to S3
        run: |
          aws s3 sync dist/ s3://skillmatchbucket --delete --acl public-read
      
     
